apiVersion: apps/v1
kind: Deployment
metadata:
  name: crosscult-country-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crosscult-country-service
  template:
    metadata:
      labels:
        app: crosscult-country-service
    spec:
      containers:
      - name: crosscult-country-service
        image: crosscultcounty.azurecr.io/crosscult-country-service:${{ github.sha }}
        ports:
        - containerPort: 80
