apiVersion: v1
kind: Service
metadata:
  name: crosscult-country-service
spec:
  selector:
    app: crosscult-country-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
